# Generated by Django 5.2.3 on 2025-07-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('participant', 'participant'), ('admin', 'Admin'), ('company', 'company')], default='participant', max_length=50)),
                ('education_level', models.CharField(max_length=255, null=True)),
                ('track', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'participant'), ('admin', 'Admin'), ('company', 'company')], default='user', max_length=50),
        ),
    ]
